export const COMMANDS = [
    {
        command: "/addlore",
        description: "Add lore to item (saves existing lore)",
        examples: ['/addlore "§6Cool sword" @s false', 'This will add lore "§6Cool sword" to the held item of @s and insert it at the top (false = add to top)'],
        keyWords: ["lore", "item", "text", "description", "add"],
    },
    {
        command: "/addblock",
        description: "Add block to multiblock",
        examples: ["/addblock stone 1 @s", "/addblock minecraft:oak_planks", "/addblock dirt 100"],
        keyWords: ["block", "multiblock", "add", "building"],
    },
    {
        command: "/setlore",
        description: "Set lore to item (replace existing lore)",
        examples: ['/setlore "§7A new description" @p', '/setlore "Line 1\\nLine 2"'],
        keyWords: ["lore", "item", "text", "description", "replace", "set"],
    },
    {
        command: "/bindcommand",
        description: "Bind command to item",
        examples: ['/bindcommand "say Hello, world!" @s', '/bindcommand "tp @s 100 64 200"'],
        keyWords: ["bind", "command", "item", "trigger", "execute"],
    },
    {
        command: "/bindfunction",
        description: "Bind function to item",
        examples: ['/bindfunction "myaddon:open_gui" @s', '/bindfunction "myaddon:reward_player"'],
        keyWords: ["bind", "function", "item", "trigger", "execute"],
    },
    {
        command: "/explosion",
        description: "Create explosion",
        examples: ["/explosion 4", "/explosion 8 100 64 200 true true"],
        keyWords: ["explosion", "blast", "destroy", "boom", "tnt"],
    },
    {
        command: "/cloneitem",
        description: "Clone item from one entity's slot to another entity's slot",
        examples: ["/cloneitem @s 0 @p 1", "/cloneitem @p 5 @a 10 3"],
        keyWords: ["clone", "item", "copy", "duplicate", "slot", "inventory"],
    },
    {
        command: "/setitemname",
        description: "Set custom name for held item",
        examples: ['/setitemname "§6Epic Sword"', '/setitemname "&rSimple Shield"'],
        keyWords: ["name", "item", "rename", "title", "custom"],
    },
    {
        command: "/clearlore",
        description: "Clear lore from item",
        examples: ["/clearlore", "/clearlore 3"],
        keyWords: ["clear", "lore", "remove", "delete", "item"],
    },
    {
        command: "/createmultiblock",
        description: "Create multi-block item with GUI",
        examples: ["/createmultiblock"],
        keyWords: ["multiblock", "create", "gui", "blocks", "item"],
    },
    {
        command: "/multiblockfill",
        description: "Fill area with multi-block from mainhand (~18000 blocks/s)",
        examples: ["/multiblockfill 100 64 200 110 70 210", "/multiblockfill ~ ~ ~ ~10 ~5 ~10"],
        keyWords: ["multiblock", "fill", "area", "fast", "async", "building"],
    },
    {
        command: "/nv",
        description: "Give night vision",
        examples: ["/nv @p 6000", "/nv"],
        keyWords: ["night", "vision", "see", "dark", "effect"],
    },
    {
        command: "/heal",
        description: "Heal player to full health/hunger",
        examples: ["/heal @p both true", "/heal"],
        keyWords: ["heal", "health", "hunger", "restore", "full"],
    },
    {
        command: "/setday",
        description: "Set specific day number",
        examples: ["/setday 42", "/setday 1"],
        keyWords: ["day", "time", "set", "calendar", "date"],
    },
    {
        command: "/spawnentity",
        description: "Spawn entities with optional equipment and effects",
        examples: ["/spawnentity zombie 5", "/spawnentity cow 3 100 64 200 @s"],
        keyWords: ["spawn", "entity", "mob", "creature", "summon"],
    },
    {
        command: "/god",
        description: "Toggle god mode (resistance 5)",
        examples: ["/god @p 12000", "/god"],
        keyWords: ["god", "invincible", "immortal", "resistance", "protection"],
    },
    {
        command: "/burnentity",
        description: "Set entity on fire",
        examples: ["/burnentity @e[type=zombie] 10", "/burnentity @p 5"],
        keyWords: ["burn", "fire", "flame", "ignite", "entity"],
    },
    {
        command: "/knockback",
        description: "Apply knockback force to entities",
        examples: ["/knockback @e[type=creeper] 2.5 90 0.6", "/knockback @p 1.2"],
        keyWords: ["knockback", "push", "force", "velocity", "launch"],
    },
    {
        command: "/durability",
        description: "Set item durability percentage",
        examples: ["/durability 50 @p", "/durability 100"],
        keyWords: ["durability", "damage", "repair", "item", "percentage"],
    },
    {
        command: "/cleararea",
        description: "Clear all entities/items in area",
        examples: ["/cleararea 20 100 64 200", "/cleararea 10"],
        keyWords: ["clear", "area", "remove", "entities", "items", "cleanup"],
    },
    {
        command: "/createpath",
        description: "Create path between waypoints with specified radius",
        examples: ["/createpath 3.5 100 64 200 120 64 220", '/createpath 2 100 64 200 110 64 210 115 64 215 "ALL" STONE'],
        keyWords: ["path", "road", "waypoint", "connect", "route", "building"],
    },
    {
        command: "/getslotitem",
        description: "Get information about item in specific slot",
        examples: ["/getslotitem 5 @p", "/getslotitem 0"],
        keyWords: ["slot", "item", "info", "inventory", "check"],
    },
    {
        command: "/findslot",
        description: "Find item locations in inventory",
        examples: ["/findslot minecraft:diamond_sword first @p", "/findslot sword all"],
        keyWords: ["find", "slot", "search", "item", "inventory", "locate"],
    },
    {
        command: "/getpathtool",
        description: "Get path creation tool (shovel)",
        examples: ["/getpathtool"],
        keyWords: ["path", "tool", "shovel", "waypoint", "building"],
    },
    {
        command: "/buildpath",
        description: "Build path using path tool data (opens GUI)",
        examples: ["/buildpath"],
        keyWords: ["build", "path", "gui", "waypoint", "construction"],
    },
    {
        command: "/configfill",
        description: "Configure block filling performance settings",
        examples: ["/configfill 1000 1 50000", "/configfill"],
        keyWords: ["config", "fill", "performance", "blocks", "settings"],
    },
    {
        command: "/buildtext",
        description: "Build 3D text from blocks with customizable options",
        examples: ['/buildtext "HELLO" 100 64 200 4 north false', '/buildtext "A"'],
        keyWords: ["text", "3d", "blocks", "font", "write", "building"],
    },
    {
        command: "/brush",
        description: "Configure and create brush tool",
        examples: ["/brush"],
        keyWords: ["brush", "tool", "paint", "sphere", "cube", "building"],
    },
    {
        command: "/largefill",
        description: "Fill large areas with blocks using async processing (up to 1M blocks)",
        examples: ["/largefill 0 64 0 10 70 10 stone outline", "/largefill 0 64 0 50 80 50 minecraft:stone replace cobblestone"],
        keyWords: ["largefill", "fill", "area", "async", "massive", "building"],
    },
    {
        command: "/fillinfo",
        description: "Calculate fill area size and estimated time",
        examples: ["/fillinfo 0 64 0 10 70 10", "/fillinfo ~ ~ ~ ~10 ~5 ~10"],
        keyWords: ["fillinfo", "calculate", "size", "estimate", "time", "area"],
    },
    {
        command: "/createfigure",
        description: "Create geometric figures (cube, sphere, cylinder, pyramid) with various options",
        examples: ["/createfigure sphere 100 64 100 stone 8 solid", "/createfigure cube 0 64 0 stone 5"],
        keyWords: ["figure", "geometry", "cube", "sphere", "cylinder", "pyramid", "shape"],
    },
    {
        command: "/gm",
        description: "Change gamemode (defaults to creative)",
        examples: ["/gm creative @p", "/gm s"],
        keyWords: ["gamemode", "creative", "survival", "adventure", "spectator", "mode"],
    },
    {
        command: "/boost",
        description: "Apply impulse boost to entities",
        examples: ["/boost 10 up @p", "/boost 2.5 forward"],
        keyWords: ["boost", "launch", "jump", "velocity", "impulse", "force"],
    },
    {
        command: "/random",
        description: "Random number",
        examples: ["/random 100 1 true", "/random 6"],
        keyWords: ["random", "number", "generate", "rng"],
    },
    {
        command: "/tlore",
        description: "Transfer lore from one item to another",
        examples: ["/tlore @s 0 @p 1", "/tlore @a 2 @s 3"],
        keyWords: ["transfer", "lore", "copy", "move", "item"],
    },
    {
        command: "/remove",
        description: "Remove entities",
        examples: ["/remove @e[type=sheep] true", "/remove @e[type=zombie]"],
        keyWords: ["remove", "delete", "kill", "entity", "clear"],
    },
    {
        command: "/surface",
        description: "Create surface patterns (circle/square) on terrain",
        examples: ["/surface circle 100 64 100 10 grass", "/surface square 0 64 0 6 stone 80 60 true"],
        keyWords: ["surface", "terrain", "pattern", "circle", "square", "ground"],
    },
    {
        command: "/plain",
        description: "Create plains by removing blocks above ground level in specified shapes",
        examples: ["/plain 100 64 100 20 circle", "/plain ~ ~ ~ 10 square"],
        keyWords: ["plain", "flatten", "terrain", "ground", "shape", "level"],
    },
    {
        command: "/worldinfo",
        description: "Get world information (time, day, moonphase, players, etc.)",
        examples: ["/worldinfo time", "/worldinfo all"],
        keyWords: ["world", "info", "time", "day", "moon", "players", "statistics"],
    },
    {
        command: "/getveintool",
        description: "Get vein tool for marking corners and exits",
        examples: ["/getveintool"],
        keyWords: ["vein", "tool", "mining", "corners", "exits", "generation"],
    },
    {
        command: "/clearveintool",
        description: "Clear all vein tool data (corners and exits)",
        examples: ["/clearveintool"],
        keyWords: ["clear", "vein", "tool", "reset", "corners", "exits"],
    },
    {
        command: "/veintoolinfo",
        description: "Show current vein tool information",
        examples: ["/veintoolinfo"],
        keyWords: ["vein", "tool", "info", "status", "corners", "exits"],
    },
    {
        command: "/generateveins",
        description: "Generate vein system using vein tool data",
        examples: ["/generateveins"],
        keyWords: ["generate", "vein", "system", "mining", "network", "cave"],
    },
    {
        command: "/hiddenblocks",
        description: "Get hidden/creative blocks",
        examples: ["/hiddenblocks"],
        keyWords: ["hidden", "blocks", "creative", "special", "command", "barrier"],
    },
    {
        command: "/copyentitytool",
        description: "Get copy entity tool",
        examples: ["/copyentitytool"],
        keyWords: ["copy", "entity", "tool", "duplicate", "clone", "mob"],
    },
    {
        command: "/loadentity",
        description: "Load entity from structure/code",
        examples: ["/loadentity 100 64 200 5 zombie", "/loadentity"],
        keyWords: ["load", "entity", "structure", "code", "spawn", "restore"],
    },
    {
        command: "/saveposition",
        description: "Save current position with a name",
        examples: ["/saveposition home_base", "/saveposition mine_entrance"],
        keyWords: ["save", "position", "location", "coordinates", "waypoint", "teleport"],
    },
    {
        command: "/tps",
        description: "Teleport to saved position",
        examples: ["/tps home_base", "/tps"],
        keyWords: ["teleport", "position", "saved", "location", "travel", "warp"],
    },
    {
        command: "/tpsg",
        description: "Teleport to saved position using GUI",
        examples: ["/tpsg"],
        keyWords: ["teleport", "gui", "position", "saved", "location", "travel", "warp"],
    },
    {
        command: "/clearpositions",
        description: "Clear all saved positions",
        examples: ["/clearpositions"],
        keyWords: ["clear", "positions", "saved", "locations", "reset"],
    },
    {
        command: "/rtp",
        description: "Random teleport within specified distance",
        examples: ["/rtp 100 2000", "/rtp"],
        keyWords: ["random", "teleport", "travel", "explore", "adventure"],
    },
    {
        command: "/help",
        description: "Show all available commands",
        examples: ["/help"],
        keyWords: ["help", "?", "how", "commands", "all"],
    },
    {
        command: "/search",
        description: "Open gui based on search",
        examples: ["/search spawn", "/search lore"],
        keyWords: ["help", "?", "how", "commands", "all", "search"],
    },
    {
        command: "/throwtagtool",
        description: "Get throw tag tool for applying tags to entities",
        examples: ["/throwtagtool"],
        keyWords: ["tag", "tool", "throw", "entity", "apply"],
    },
    {
        command: "/tagtooladd",
        description: "Add tag to throw tag tool",
        examples: ["/tagtooladd enemy", "/tagtooladd boss"],
        keyWords: ["tag", "tool", "add", "entity"],
    },
    {
        command: "/tagtoolremove",
        description: "Remove tag from throw tag tool",
        examples: ["/tagtoolremove enemy", "/tagtoolremove boss"],
        keyWords: ["tag", "tool", "remove", "entity"],
    },
    {
        command: "/tagtoolclear",
        description: "Remove all tags from throw tag tool",
        examples: ["/tagtoolclear"],
        keyWords: ["tag", "tool", "clear", "entity"],
    },
    {
        command: "/removetagtool",
        description: "Get remove tag tool for removing tags from entities",
        examples: ["/removetagtool"],
        keyWords: ["tag", "tool", "remove", "entity", "get"],
    },
    {
        command: "/copypastetool",
        description: "Get copy paste tool for structure operations",
        examples: ["/copypastetool"],
        keyWords: ["copy", "paste", "tool", "structure", "building"],
    },
    {
        command: "/setpos",
        description: "Set position for copy paste tool",
        examples: ["/setpos 100 64 100 110 70 110", "/setpos ~ ~ ~ ~10 ~5 ~10"],
        keyWords: ["setpos", "position", "tool", "copy", "paste"],
    },
    {
        command: "/pos1",
        description: "Set position 1 for copy paste tool",
        examples: ["/pos1", "/pos1 100 64 100"],
        keyWords: ["pos1", "position", "tool", "copy", "paste"],
    },
    {
        command: "/pos2",
        description: "Set position 2 for copy paste tool",
        examples: ["/pos2", "/pos2 120 70 120"],
        keyWords: ["pos2", "position", "tool", "copy", "paste"],
    },
    {
        command: "/clearpos",
        description: "Clear saved positions for copy paste tool",
        examples: ["/clearpos"],
        keyWords: ["clearpos", "position", "tool", "copy", "paste"],
    },
    {
        command: "/copy",
        description: "Copy selected area as structure",
        examples: ["/copy true", "/copy"],
        keyWords: ["copy", "structure", "area", "building"],
    },
    {
        command: "/paste",
        description: "Paste copied structure at location",
        examples: ["/paste 120 70 120", "/paste"],
        keyWords: ["paste", "structure", "area", "building"],
    },
    {
        command: "/cut",
        description: "Cut selected area (copy + clear original)",
        examples: ["/cut true", "/cut"],
        keyWords: ["cut", "structure", "area", "building"],
    },
    {
        command: "/move",
        description: "Move selected area to new location",
        examples: ["/move 200 64 200 true", "/move 100 64 100"],
        keyWords: ["move", "structure", "area", "building"],
    },
    {
        command: "/math",
        description: "Evaluate mathematical expressions (unrestricted - creative mode only)",
        examples: ["/math (2+3)*4", "/math 3.5+1.5"],
        keyWords: ["math", "calculate", "expression", "creative"],
    },
    {
        command: "/mathsafe",
        description: "Evaluate safe mathematical expressions",
        examples: ["/mathsafe 2+2", "/mathsafe max(1,5)"],
        keyWords: ["math", "calculate", "expression", "safe"],
    },
    {
        command: "/mathhelp",
        description: "Show available mathematical functions",
        examples: ["/mathhelp"],
        keyWords: ["math", "help", "functions", "list"],
    },
    {
        command: "/convert",
        description: "Convert between common units",
        examples: ["/convert 1000 m km", "/convert 10 kg g"],
        keyWords: ["convert", "unit", "value", "measurement"],
    },
    {
        command: "/calc",
        description: "Quick calculator (alias for mathsafe)",
        examples: ["/calc 1+1", "/calc 12*3"],
        keyWords: ["calc", "calculate", "math", "expression"],
    },
    {
        command: "/freeze",
        description: "Freeze player for specific time",
        examples: ['/freeze @p true "You are frozen" 30', "/freeze @a"],
        keyWords: ["freeze", "jail", "punish", "stop", "player"],
    },
    {
        command: "/unfreeze",
        description: "Unfreeze player",
        examples: ['/unfreeze @p true "Welcome back"', "/unfreeze @a"],
        keyWords: ["freeze", "jail", "punish", "stop", "player", "unfreeze"],
    },
    {
        command: "/replaceloreline",
        description: "Replace lore at specific line index",
        examples: ['/replaceloreline 2 "New lore text" @p', '/replaceloreline 0 "First line"'],
        keyWords: ["lore", "text", "item", "replace", "line"],
    },
    {
        command: "/replacelorelinefind",
        description: "Replace lore line by finding text match",
        examples: ['/replacelorelinefind "old" "new" @p', '/replacelorelinefind "§7" "§6"'],
        keyWords: ["lore", "text", "item", "replace", "line"],
    },
    {
        command: "/showlore",
        description: "Display item lore with line numbers",
        examples: ["/showlore @p", "/showlore"],
        keyWords: ["lore", "text", "item", "line"],
    },
    {
        command: "/showcommandlogs",
        description: "Enable or disable display of command logs",
        examples: ["/showcommandlogs true", "/showcommandlogs false"],
        keyWords: ["log", "display", "command", "output", "show", "text", "chat"],
    },
    {
        command: "system",
        description: "Allow running commands and scripts as system (OP) user",
        examples: [
            "/system run script 'world.getPlayers().forEach(p => p.sendMessage(\"Hello from system!\"))'",
            "/system runInterval script 'sendMessage(\"System message every 10s\")' 200 10",
            "/system run command 'say Hello from system!'",
        ],
        keyWords: ["system", "op", "admin", "commands", "scripts", "run"],
    },
    {
        command: "aliascreate",
        description: "Create command alias",
        examples: ['/aliascreate greet say "Hello, world!"', '/aliascreate healme "heal @s both true"'],
        keyWords: ["alias", "create", "command", "shortcut", "custom", "bind", "macro"],
    },
    {
        command: "aliasdelete",
        description: "Delete command alias",
        examples: ["/aliasdelete greet", "/aliasdelete healme"],
        keyWords: ["alias", "delete", "command", "remove", "shortcut", "custom"],
    },
    {
        command: "al",
        description: "Execute command alias",
        examples: ["/al greet", "/al healme"],
        keyWords: ["alias", "execute", "command", "shortcut", "custom", "run"],
    },
    {
        command: "createMultiblockHB",
        description: "Create multi-block item from items in hotbar, or you can select range of slots",
        examples: ["/createMultiblockHB 0 35", "/createMultiblockHB"],
        keyWords: ["multiblock", "create", "hotbar", "blocks", "item"],
    },
    {
        command: "variables",
        description: "Manage custom global variables for use in commands and scripts",
        examples: ["/system run script \"Variables.set('myVar', 42)\"", "/system run script \"Variables.get('myVar')\"", "/system run script \"Variables.delete('myVar')\""],
        keyWords: ["variables", "custom", "manage", "set", "get", "delete", "list"],
    },
];
